[
    {
        "productid": "7D6A083B-01C4-4E74-9F10-2916543188B8",
        "sku": "WildWorkout",
        "productname": "<b>Wild Workout®</b>",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "courses",
        "header": "Workout System Copies How Wild Animals Do It",
        "shortdesc": "Exercise System based on the principles of how the wild animals exercise in the wild",
        "description": "Exercises based on the principles of how the wild animals stay in shape. In the Wild Workout&#174; Mobile App we selected wild animals with massive strength in certain areas of their bodies to develop a total body workout of 45 muscle building, fat burning, body shaping exercises like no other that will have the jaws of others dropping in disbelief and envy.",
        "link": "http://www.software-rus.com/simulator2.html?app=wildworkout",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "wildworkout.png",
        "carousel": true,
        "carousel_caption": "<b>Wild Workout®</b>",
        "tube": "youtube",
        "videoid": "YyZNIarRYSc",
        "showvideo": true,
        "unitprice": 49.95,
        "saleprice": 49.95,
        "unitsinstock": 22,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 1
    },
    {
        "productid": "7B8BCC0B-2616-4A72-89E2-DA51E2FDD935",
        "sku": "free_movies",
        "productname": "<b>Over 1 MILLION Views</b>",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "<b>Over 1 MILLION Views</b> - FREE Movie Channels",
        "shortdesc": "Get thousands of Free Movie Channels and access to Hidden TV Stations foe FREE",
        "description": "Get thousands of Free Movie Channels and access to Hidden TV Stations foe FREE",
        "link": "",
        "linktext": "try it",
        "imageurl": null,
        "imagename": "freemovies.jpg",
        "carousel": true,
        "carousel_caption": "<b>Over 1 MILLION Views</b>",
        "tube": "youtube",
        "videoid": "HppJHKwCGCo",
        "showvideo": true,
        "unitprice": 0,
        "saleprice": 0,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 1
    },
    {
        "productid": "451E17E4-4688-48DC-9956-28F124A93863",
        "sku": "Malibu_Diet",
        "productname": "<b>Malibu Diet®</b>",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "<b>Malibu Diet®</b> - is now World's Leading Diet",
        "shortdesc": "Meet <b>Bill SerGio</b> who has created and sold over $1 Billion worth of diet products",
        "description": "<b>Malibu Diet®</b> - is now World's Leading Diet",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "malibu.jpg",
        "carousel": true,
        "carousel_caption": "<b>Malibu Diet®</b>",
        "tube": "youtube",
        "videoid": "j2vfP7U-LBI",
        "showvideo": true,
        "unitprice": 49.95,
        "saleprice": 49.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 2
    },
    {
        "productid": "a0427b1d-17fb-43fb-be1a-5d65a4d8e831",
        "sku": "maxpay",
        "productname": "Max2PayTV<b style=\"color: rgb(85, 85, 85);background-color: rgb(255, 255, 255);\"><b>® </b></b>Software",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "software",
        "header": "Max2PayTV® - Shows Max to Pay for TV Time",
        "shortdesc": "Bill SerGio this amazing software that shows the Max amount to Pay for TV Time",
        "description": "Most half hours on NBC, ABC, CBS, and FOX stations sell for $20 to $300.  By Federal Law all TV and radio time MUST be sold through an AUCTION. Your ad agency has no motivation to buy the time cheaper cheaper because that would mean less money for your ad agency.  Stop Getting Ripped Off!  Our software will tell you the maximum amount to bid and pay on any station for a half hour of infomercial TV time.  Includes our database with over 28,000 stations and our software tells you exactly how much to pay on EACH TV station.  It also tells you which stations generate the most sales compared to all the other stations. Out of the 28,000 TV stations in our database it turns out that ONLY about 900 TV stations are worth buying to air TV commercials in our experience!  On those NBC, ABC, CBS and FOX TV Stations prices for the BEST Half Hours of TV time range from $20 to $300 per Half Hour. <a href=\"https://www.youtube.com/watch?v=pEXX74lGYuY\" target=\"_blank\" class=\"btn btn-xs-success btn-small\">Watch Video</a>",
        "link": "",
        "linktext": "try it",
        "imageurl": null,
        "imagename": "maxpay.png",
        "carousel": false,
        "carousel_caption": "Bill SerGio's Max2PayTV®",
        "tube": "youtube",
        "videoid": "pEXX74lGYuY",
        "showvideo": true,
        "unitprice": 350,
        "saleprice": 350,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 2
    },
    {
        "productid": "03734A78-578C-4C7A-A662-9E8720A41F73",
        "sku": "Kitty_Toilet_Trainer",
        "productname": "Kitty Toilet Trainer®",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "Bill SerGio Invented... <em>The Kitty Toilet Trainer®</em>",
        "shortdesc": "The Kitty Toilet Trainer® was created by Bill SerGio back in 1970 and is STILL being sold",
        "description": "The Kitty Toilet Trainer® was created by Bill SerGio back in 1970 and is STILL being sold today. Bill SerGio's amazing toilet training system will toilet train ANY cat to use the toilet and flush the toilet with their paws in less than 3 days.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "kitty_toilet_trainer.jpg",
        "carousel": false,
        "carousel_caption": "Toilet Train Your Cat in Just Days!",
        "tube": "",
        "videoid": "",
        "showvideo": false,
        "unitprice": 19.95,
        "saleprice": 19.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 3
    },
    {
        "productid": "1732B8E6-FA89-43DE-A9B2-81DC3EBD1427",
        "sku": "Watch_Camera",
        "productname": "Watch Camera with Built-in DVR & Audio",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "Watch Camera with Built-in HD DVR & Stereo Audio",
        "shortdesc": "Fully functional, micro, all-in-one surveillance system. Our Watch Camera is a state of the art, body-worn, complete surveillance system. This wire-free wristwatch contains the latest in miniaturized video technology.",
        "description": "Fully functional, micro, all-in-one surveillance system. Our Watch Camera is a state of the art, body-worn, complete surveillance system. This wire-free wristwatch contains the latest in miniaturized video technology. We've squeezed a color camera, microphone, power source and a 4 GB digital video recorder inside a stylish silver watch. The watch is also fully functional. Just slide the watch on your wrist, press the power switch and go. Perfect for covert evidence collection or hidden investigation or surveillance assignments. When you are ready to view the video or recharge the built-in lithium battery (full battery runs 2 hours), simply plug the watch into your computer's USB port.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "watch_camera.jpg",
        "carousel": false,
        "carousel_caption": "Watch Camera with Built-in DVR & Audio",
        "tube": "",
        "videoid": "",
        "showvideo": false,
        "unitprice": 118,
        "saleprice": 118,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 5
    },
    {
        "productid": "79734C63-97EB-4DEE-BBEF-D4704F321B3E",
        "sku": "VisibleHair",
        "productname": "VisibleHair&#174;",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "Eliminate Baldness in Just Seconds with Visible Hair&#174;",
        "shortdesc": "Unlike other products, Visible Hair® is made up of natural hair-like fibers that bind both to the hair follicle and to the scalp to give the real appearance of fuller, thicker hair!",
        "description": "Unlike other products, Visible Hair® is made up of natural hair-like fibers that bind both to the hair follicle and to the scalp to give the real appearance of fuller, thicker hair!",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "visiblehair.png",
        "carousel": false,
        "carousel_caption": "Eliminate Baldness in Just Seconds with Visible Hair&#174;",
        "tube": "youtube",
        "videoid": "9wIZnhDikMo",
        "showvideo": true,
        "unitprice": 29.95,
        "saleprice": 29.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 7
    },
    {
        "productid": "965A30EC-E1DF-4B94-AFE8-2FEB8D1D4574",
        "sku": "superman_001",
        "productname": "Superman #1",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "comics",
        "header": "Superman #1 - Origin of the Man of Steel himself",
        "shortdesc": "Superman #1 (DC, 1939). The Golden Age blockbuster launche dthe Man of Steel",
        "description": "Superman #1 (DC, 1939) CGC GD/VG 3.0 Off-white pages. It's the nicest copy of the Golden Age blockbuster that we've offered in more than two years! There are just not that many copies available in nice grades. Soon after Superman's debut in Action Comics #1, it was apparent that one title for the Man of Tomorrow wasn't enough. So, barely a year later, DC gave him his own title.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "comics/superman_001.png",
        "carousel": true,
        "carousel_caption": "Superman #1",
        "tube": "youtube",
        "videoid": "",
        "showvideo": false,
        "unitprice": 3700000,
        "saleprice": 3700000,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 4
    },
    {
        "productid": "03B9FD82-0275-4154-8BD7-A2EAD16E7407",
        "sku": "batman_001",
        "productname": "Batman #1",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "comics",
        "header": "Batman #1",
        "shortdesc": "The first comic dedicated exclusively to The Dark Knight! This 1940 issue pitted the Dynamic Duo against classic menaces including Professor Hugo Strange. Plus, the first appearances of The Joker and Catwoman (referred to as&#34;the Cat&#34;)! Also includes a 2-page retelling of Batman's origin.",
        "description": "The first comic dedicated exclusively to The Dark Knight! This 1940 issue pitted the Dynamic Duo against classic menaces including Professor Hugo Strange. Plus, the first appearances of The Joker and Catwoman (referred to as&#34;the Cat&#34;)! Also includes a 2-page retelling of Batman's origin.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "comics/batman_001.png",
        "carousel": false,
        "carousel_caption": "Batman #1",
        "tube": "youtube",
        "videoid": "R3k0d7tTkhU",
        "showvideo": false,
        "unitprice": 1290000.00,
        "saleprice": 1290000.00,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 4
    },
    {
        "productid": "7650EEA2-B2CF-4993-AAFD-12C0D8214568",
        "sku": "tv_marketing",
        "productname": "Complete Guide to<br />TV Marketing",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "courses",
        "header": "Sell Your Product on TV for FREE",
        "shortdesc": "In this course we show you how to air your TV commercials without buying any TV time. It's called P.I.or Per Inquiry. That's Right! You simply pay the TV stations a percentage of what your commercials sell which <strong>GUARANTEES YOU</strong> a <strong>NET PROFIT</strong>.<br /><a class=\"btn-x-blue\" href=\"https://www.youtube.com/watch?v=92eR46ZbMAg\" target=\"_blank\"><span style=\"padding: 0px 8px 0px 8px !important;\">Watch Video</span></a>",
        "description": "You can put a 30-second or 60-second TV commercial for FREE---no kidding. It's called Per Inquiry where you pay the TV stations a percentage of what you sell.  This course will teach you how to contact TV stations, and which stations to contact.<br /><a href=\"https://www.youtube.com/watch?v=92eR46ZbMAg\" target=\"_blank\">Watch Video</a>",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "tv_course.png",
        "carousel": true,
        "carousel_caption": "Buy Half Hours of TV Time on NBC, ABC, CBS & FOX for as Little as $20.",
        "tube": "youtube",
        "videoid": "",
        "showvideo": false,
        "unitprice": 49.95,
        "saleprice": 49.85,
        "unitsinstock": 22,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 4
    },
    {
        "productid": "9744494B-98DB-4E42-A657-1A1BC1EE5967",
        "sku": "internet_marketing",
        "productname": "Complete Guide to<br />Internet Marketing",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "courses",
        "header": "Get Multiple Listings on the FIRST Page of Google",
        "shortdesc": "This course reveals the secrets like creating <strong><em><span style=\"color:#c00000;\">Pseudo Domains</span></em></strong> to get at the top of the search engines. And how to use special tags to legally get <strong><em>500,000 targeted YouTube views</em></strong>&nbsp;without violating YouTube's Terms of Service.",
        "description": "One day I got a call from a young man who asked me if I could build him a website like his uncle's website and get his website listed number one on the search engines like Yahoo and Google. His uncle sold Lamps and he wanted a website like his uncle's that came up number one in all the search engines. I looked at his uncle's website and told the young man that I could create a similar website for him that be listed at the top of the organic section of Google and Yahoo on any searches for lamps. You are probably saying to yourself at this point... How is that possible? It can't be done! But it can be done because searches for lamps lend themselves to pseudo domains. A pseudo domain is a term used among a handful of developers like myself and it simply means a directory name with a space in the that can't be registered as a domain because of the space, i.e., domain names can't have spaces but folders, i.e., directories on servers can have a space in their names. The first thing I realized when I saw the uncle's lamp website selling lamps was that the main buyers of these lamps were interior designers who had the catalogs of all the lamp manufacturers but could not buy the lamps directly from the manufacturer--they had to find lamp distributors on the Internet. And they would do a search in Yahoo or Google using the name of the manufacturer, a space and the product id number. For example, they might type in: Crystal Lamps, Inc. Stone Lamp number 45789 into a search engine. Obviously their is NO domain with this name because of the spaces BUT if the uncle's website had a directory with this name and a file inside the directory with this name as well which resulted several types of search engines indexing this as what we call a pseudo domain so that anyone typing this into a search engine would immediately see the uncle's website listed at the top of the organic section. Of course, not all products are searched for in this way but those that are can easily be placed at the top of search engines legally by simply creating these pseudo domains. This course will reveal the tricks used by the most successful websites to We show you dozens of tricks like how to legally get 500,000 targeted YouTube views without violating YouTube's Terms of Service.  We explain how to setup 301 Redirect Domains with the correct search Terms and much more! We reveal all the legal tricks nobody else will tell you about.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "internet_course.png",
        "carousel": true,
        "carousel_caption": "Get Multiple Listings on the FIRST Page of Google & Other Search Engines!",
        "tube": "youtube",
        "videoid": "",
        "showvideo": false,
        "unitprice": 49.95,
        "saleprice": 49.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 4
    },
    {
        "productid": "265b72f5-747c-4ab2-ab6f-ed56a77bad8e",
        "sku": "contract_collection",
        "productname": "Contract Collection&#153;",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "courses",
        "header": "Over 100 Professional Business Contracts for Internet & TV Marketing",
        "shortdesc": "Includes a collection of sample contracts written over the years by attorneys we hired.  Purchased separately this collection of contracts <strong>would cost you <span style=\"color: #c00000;\">over $10,000</span>.</strong>  These contracts cover virtually every aspect of TV and Internet marketing.",
        "description": "Includes a collection of sample contracts written over the years by attorneys we hired.  Purchased separately this collection of contracts <strong>would cost you <span style=\"color: #c00000;\">over $10,000</span>.</strong>  These contracts cover virtually every aspect of TV and Internet marketing.",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "contracts.png",
        "carousel": true,
        "carousel_caption": "Over 100 Professional Business Contracts for Internet & TV Marketing",
        "tube": "youtube",
        "videoid": "",
        "showvideo": false,
        "unitprice": 49.95,
        "saleprice": 49.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 4
    },
    {
        "productid": "1782876F-C093-4354-A543-5DC52349ED9A",
        "sku": "SpyWhacker",
        "productname": "Spy Whacker&#153;",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "software",
        "header": "Don't Let the Bastards Bust You!",
        "shortdesc": "Police and F.B.I. are installing black boxes in many ISPs to record your Internet surfing and downloads for evidence. Kids are being prosecuted and parents are being financially bankrupted from costly legal fees!  Every file, image, video you have is secretly logged in your computer. Whacker&#153; PERMANENTLY removes files that have your identity and everything you do like surfing and downloads so that they CAN'T be recovered by any anyone using any means!",
        "description": "Police and F.B.I. are installing black boxes in many ISPs to record your Internet surfing and downloads for evidence. Kids are being prosecuted and parents are being financially bankrupted from costly legal fees!  Every file, image, video you have is secretly logged in your computer. Whacker&#153; PERMANENTLY removes files that have your identity and everything you do like surfing and downloads so that they CAN'T be recovered by any anyone using any means!",
        "link": "",
        "linktext": "download it",
        "imageurl": "",
        "imagename": "securityguard.jpg",
        "carousel": false,
        "carousel_caption": "Don't Let the Bastards Bust You!",
        "tube": "",
        "videoid": "",
        "showvideo": false,
        "unitprice": 49.95,
        "saleprice": 49.95,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 13
    },
    {
        "productid": "804AA015-48EA-462B-A1D4-2C05815947D7",
        "sku": "flash_001",
        "productname": "Flash #1",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "comics",
        "header": "Flash #1",
        "shortdesc": "Flash Comics was an anthology comic book published by All-American Publications and later National Periodicals (DC Comics).",
        "description": "Flash Comics was an anthology comic book published by All-American Publications and later National Periodicals (DC Comics).",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "comics/flash_001.png",
        "carousel": true,
        "carousel_caption": "Flash #1",
        "tube": "",
        "videoid": "",
        "showvideo": false,
        "unitprice": 27500.00,
        "saleprice": 27500.00,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 2
    },
    {
        "productid": "19A9C05D-0A5B-460C-BF3F-20404650F539",
        "sku": "action_001",
        "productname": "Action #1",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "comics",
        "header": "Action Comics is an American comic book series that introduced Superman",
        "shortdesc": "Action Comics is an American comic book series that introduced Superman",
        "description": "Action Comics is an American comic book series that introduced Superman",
        "link": "",
        "linktext": "try it",
        "imageurl": "",
        "imagename": "comics/action_001.png",
        "carousel": false,
        "carousel_caption": "Action #1",
        "tube": "",
        "videoid": "",
        "showvideo": false,
        "unitprice": 1200000.00,
        "saleprice": 1200000.00,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 3
    },
    {
        "productid": "71EE2BC3-5CF3-4CCC-B35F-BF851D2519AB",
        "sku": "dont_pay_that_bill",
        "productname": "Don't Pay That Bill",
        "storeid": "7cc6cb94-0938-4675-b84e-6b97ada53978",
        "categoryname": "cool",
        "header": "Don't Pay That Bill",
        "shortdesc": "Most debts are already past the Statute of Limitations in your state which means that debt can NO longer take you to court to collect that debt.",
        "description": "Most debts are already past the Statute of Limitations in your state which means that debt can NO longer take you to court to collect that debt. If you make any payments on that debt you may re-start the clock on that debt. Find our if your debts are past the Statute of Limitations in your state and you should think twice before making any payments on debts past the Statute of Limitations. We DO NOT sell any products or services related to debt or getting out of debt or improving your credit rating. NOBODY can improve your credit rating. We suggest you visit the Federal Trade Commission website to learn more about what you can do to fight unethical Bill Collectors.",
        "link": "",
        "linktext": "try it",
        "imageurl": null,
        "imagename": "dont_pay_that_bill.jpg",
        "carousel": false,
        "carousel_caption": "Don't Pay That Bill",
        "tube": "youtube",
        "videoid": "Lt-XYuBnJig",
        "showvideo": true,
        "unitprice": 0,
        "saleprice": 0,
        "unitsinstock": 1,
        "unitsonorder": 1,
        "reorderlevel": 1,
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "discontinued": false,
        "notes": "",
        "faux": false,
        "sortorder": 5
    }
]